version: "3.8"
services:
    api:
        build: ./server
        container_name: api_c
        ports:
            - 4000:4000
        volumes:
            - ./server:/api
            - /api/node_modules
            - /api/dist
        environment:
            PORT: 4000
            DB_URL: mongodb+srv://raaziTyping:thisIsAStrongPassword@cluster0.6a4yhtt.mongodb.net/?retryWrites=true&w=majority

    web:
        build: ./client
        container_name: web_c
        ports:
            - 8080:8080
        volumes:
            - ./client:/web
            - /web/node_modules

volumes:
    app-data:
